-- QAi Talks Database Schema for Cloudflare D1
-- Generated from Prisma schema for SQLite

-- BlogPost table
CREATE TABLE "BlogPost" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL UNIQUE,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "authorName" TEXT,
    "image" TEXT,
    "published" INTEGER NOT NULL DEFAULT 0,
    "publishedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

CREATE INDEX "BlogPost_slug_idx" ON "BlogPost"("slug");
CREATE INDEX "BlogPost_published_idx" ON "BlogPost"("published");

-- Knowledge Base for RAG (Retrieval-Augmented Generation)
CREATE TABLE IF NOT EXISTS knowledge_base (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    embedding TEXT NOT NULL -- JSON stringified array
);

-- Example content rows (insert with embeddings generated offline)
-- Replace embeddings with actual values generated by Gemini or other embedding model
INSERT INTO knowledge_base (content, embedding) VALUES
    ('UK CV best practices: Use British English, avoid tables, focus on quantifiable achievements.', '[0.01,0.02]'),
    ('ATS optimization tips: Match keywords from job description, use clear section headers.', '[0.03,0.04]'),
    ('STAR interview method: Situation, Task, Action, Result. Prepare answers for common competencies.', '[0.05,0.06]'),
    ('Tech industry CV advice: Highlight relevant projects, certifications, and skills.', '[0.07,0.08]'),
    ('Finance CV advice: Emphasize regulatory knowledge, analytical skills, and quantifiable results.', '[0.09,0.10]'),
    ('Healthcare CV advice: Focus on patient outcomes, compliance, and teamwork.', '[0.11,0.12]');
