/**
 * QA Domain: Complete Role Definitions
 * Covers all 13 QA/Testing roles from Junior Tester to QA Director
 * Each role includes skills, tools, keywords, certifications, and responsibilities
 */

export interface QARole {
  id: string;
  title: string;
  category: 'core' | 'specialized' | 'strategic';
  level: 'entry' | 'mid' | 'senior' | 'lead' | 'executive';
  description: string;
  keyResponsibilities: string[];
  coreSkills: string[];
  technicalTools: string[];
  certifications: string[];
  yearsExperience: { min: number; max: number };
  keywords: string[];
  interviewFocusAreas: string[];
}

export const QA_ROLES: Record<string, QARole> = {
  // CORE ENGINEERING & FUNCTIONAL ROLES
  
  junior_qa_tester: {
    id: 'junior_qa_tester',
    title: 'Junior Software Tester / QA Intern',
    category: 'core',
    level: 'entry',
    description: 'Entry-level role focused on learning the product, executing manual test cases, and reporting clear, reproducible defects.',
    keyResponsibilities: [
      'Execute predefined test cases manually',
      'Report defects with clear reproduction steps',
      'Learn product functionality and business requirements',
      'Participate in test planning sessions',
      'Maintain test documentation',
      'Perform regression testing',
      'Escalate critical issues appropriately',
    ],
    coreSkills: [
      'Manual testing techniques',
      'Test case design basics',
      'Defect reporting and documentation',
      'Basic SQL knowledge',
      'Attention to detail',
      'Communication skills',
      'Problem-solving mindset',
    ],
    technicalTools: [
      'Test case management (TestRail, Zephyr, Azure Test Plans)',
      'Defect tracking (Jira, Azure DevOps)',
      'Postman or Insomnia (basic API testing)',
      'Browser DevTools',
      'Git (basic)',
    ],
    certifications: [
      'ISTQB Foundation Level (recommended)',
      'ISTQB Agile Tester (optional)',
    ],
    yearsExperience: { min: 0, max: 2 },
    keywords: [
      'manual testing',
      'test execution',
      'defect reporting',
      'regression testing',
      'exploratory testing',
      'test cases',
      'QA fundamentals',
      'Agile/Scrum',
    ],
    interviewFocusAreas: [
      'Why do you want to be a QA engineer?',
      'How would you report a bug you found?',
      'What is the difference between a defect and a test case?',
      'Describe your approach to exploratory testing',
      'Tell me about a time you found a critical bug and how you reported it',
    ],
  },

  qa_analyst: {
    id: 'qa_analyst',
    title: 'QA Analyst (Manual Tester)',
    category: 'core',
    level: 'mid',
    description: 'Specialises in exploratory testing and user-centric validation. Ensures software meets business requirements and handles complex edge cases that automation misses.',
    keyResponsibilities: [
      'Design and execute comprehensive test strategies',
      'Perform exploratory testing to uncover hidden defects',
      'Validate business requirements and acceptance criteria',
      'Collaborate with product managers on requirements clarification',
      'Create end-to-end test scenarios',
      'Document test evidence and results',
      'Mentor junior testers',
      'Identify and escalate quality risks',
    ],
    coreSkills: [
      'Test strategy and planning',
      'Exploratory testing expertise',
      'User-centric testing mindset',
      'Business analysis basics',
      'Risk-based testing',
      'SQL query writing',
      'API testing (REST basics)',
      'Advanced defect documentation',
      'Soft skills and stakeholder management',
    ],
    technicalTools: [
      'Test management tools (TestRail, Zephyr, Azure Test Plans)',
      'Defect tracking (Jira, Azure DevOps)',
      'Postman or Insomnia (intermediate API testing)',
      'SQL databases (MySQL, PostgreSQL)',
      'Browser DevTools and extensions',
      'Charles Proxy or Fiddler (traffic inspection)',
      'Git basics',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Agile Tester (recommended)',
      'Advanced test case design certifications',
    ],
    yearsExperience: { min: 2, max: 5 },
    keywords: [
      'exploratory testing',
      'user-centric testing',
      'test strategy',
      'business requirements',
      'edge case testing',
      'risk-based testing',
      'test scenarios',
      'acceptance criteria',
      'user acceptance testing',
      'manual QA',
    ],
    interviewFocusAreas: [
      'How do you approach exploratory testing for a new feature?',
      'Describe your process for designing comprehensive test cases',
      'How would you identify edge cases and corner cases?',
      'Tell me about a time you found a critical bug through exploratory testing',
      'How do you balance manual and automated testing?',
      'What makes a good test case?',
    ],
  },

  qa_engineer: {
    id: 'qa_engineer',
    title: 'QA Engineer',
    category: 'core',
    level: 'mid',
    description: 'Versatile role balancing manual testing with basic automation scripting. Often embedded within Agile squads handling the full testing lifecycle.',
    keyResponsibilities: [
      'Design and execute manual test cases',
      'Develop and maintain automation scripts in basic frameworks',
      'Participate in sprint planning and agile ceremonies',
      'Collaborate with developers on testability improvements',
      'Execute both manual and automated regression testing',
      'Identify automation opportunities',
      'Create and maintain test documentation',
      'Contribute to test infrastructure improvements',
    ],
    coreSkills: [
      'Manual testing expertise',
      'Basic automation scripting (JavaScript, Python, or similar)',
      'Test case design and strategy',
      'Agile/Scrum methodologies',
      'Problem-solving and debugging',
      'Communication and collaboration',
      'Version control (Git)',
      'SQL query writing',
      'API testing proficiency',
    ],
    technicalTools: [
      'Test automation frameworks (Selenium, Cypress, Playwright - basic)',
      'Test management (TestRail, Zephyr, Azure Test Plans)',
      'Defect tracking (Jira, Azure DevOps)',
      'CI/CD basics (GitHub Actions, Jenkins, GitLab CI)',
      'Postman or REST Assured (API testing)',
      'Version control (Git, GitHub, GitLab)',
      'SQL database tools',
      'Browser DevTools',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Agile Tester (recommended)',
      'Basic automation certifications',
    ],
    yearsExperience: { min: 2, max: 7 },
    keywords: [
      'QA engineer',
      'test automation basics',
      'manual testing',
      'Agile testing',
      'test planning',
      'Selenium basics',
      'Cypress basics',
      'regression testing',
      'test case design',
      'full testing lifecycle',
    ],
    interviewFocusAreas: [
      'How do you decide what to automate vs what to test manually?',
      'Tell me about your experience with Selenium/Cypress/Playwright',
      'Describe your experience in an Agile environment',
      'How do you approach creating automated test scripts?',
      'What metrics do you use to measure testing effectiveness?',
      'How do you handle flaky automated tests?',
    ],
  },

  automation_engineer: {
    id: 'automation_engineer',
    title: 'Automation Engineer',
    category: 'core',
    level: 'mid',
    description: 'Primarily responsible for developing, maintaining, and scaling automated regression suites using frameworks like Playwright, Selenium, or Cypress.',
    keyResponsibilities: [
      'Design and develop automation frameworks and test suites',
      'Maintain and scale automated regression testing',
      'Optimize automation execution and reporting',
      'Implement CI/CD integration for automated tests',
      'Debug and fix flaky tests',
      'Code reviews for test automation',
      'Mentor junior automation engineers',
      'Document automation strategy and processes',
      'Performance optimization of test suites',
    ],
    coreSkills: [
      'Advanced programming in JavaScript, Python, Java, or C#',
      'Test automation framework design',
      'Advanced Selenium/Cypress/Playwright expertise',
      'Page Object Model and design patterns',
      'CI/CD pipeline integration',
      'Debugging and problem-solving',
      'Version control and Git workflows',
      'SQL and database testing',
      'API and service testing',
    ],
    technicalTools: [
      'Selenium WebDriver (advanced)',
      'Cypress (advanced)',
      'Playwright (advanced)',
      'TestNG, Pytest, or NUnit frameworks',
      'Page Object Model implementations',
      'CI/CD platforms (Jenkins, GitHub Actions, GitLab CI, Azure Pipelines)',
      'Test reporting tools (Allure, Extent Reports)',
      'Postman or REST Assured',
      'Docker and containerization basics',
      'Version control (Git, GitHub, GitLab)',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Level – Automation Engineer (recommended)',
      'Selenium or Cypress certifications',
    ],
    yearsExperience: { min: 3, max: 10 },
    keywords: [
      'automation engineer',
      'Selenium advanced',
      'Cypress advanced',
      'Playwright advanced',
      'test frameworks',
      'CI/CD integration',
      'automation architecture',
      'Page Object Model',
      'test reporting',
      'regression automation',
      'test data management',
    ],
    interviewFocusAreas: [
      'Design an automation framework for a web application',
      'How do you handle flaky tests in your automation suite?',
      'Describe your approach to test data management',
      'What is the Page Object Model and how do you implement it?',
      'How do you optimize test execution time?',
      'Tell me about your CI/CD integration experience',
      'How do you handle cross-browser testing?',
    ],
  },

  sdet: {
    id: 'sdet',
    title: 'SDET (Software Development Engineer in Test)',
    category: 'core',
    level: 'senior',
    description: 'Highly technical developer-tester. Builds underlying test infrastructure, designs custom automation frameworks, and contributes to the application codebase to improve testability.',
    keyResponsibilities: [
      'Design and build custom test automation frameworks',
      'Architect scalable testing infrastructure',
      'Contribute to application codebase for testability',
      'Implement advanced testing patterns and practices',
      'Mentor automation engineers and developers',
      'Lead automation strategy across teams',
      'Optimize CI/CD pipelines for testing',
      'Develop test utilities and libraries',
      'Performance and load testing on automation infrastructure',
    ],
    coreSkills: [
      'Advanced software development (Java, Python, C#, Go, Rust)',
      'Advanced test automation architecture',
      'Software design patterns and best practices',
      'Microservices testing',
      'CI/CD pipeline design',
      'Docker, Kubernetes basics',
      'Database design and optimization',
      'API testing and contract testing',
      'Code refactoring and technical debt management',
    ],
    technicalTools: [
      'Advanced Selenium/Cypress/Playwright',
      'Appium for mobile automation',
      'REST Assured for API testing',
      'GraphQL testing',
      'Mock servers and service virtualization',
      'Docker and Kubernetes',
      'Jenkins, GitLab CI, GitHub Actions (advanced)',
      'Allure, ExtentReports, custom frameworks',
      'Contract testing (Pact, Spring Cloud Contract)',
      'Time-series databases (InfluxDB, Prometheus)',
      'Git, GitHub, GitLab (advanced)',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Level – Automation Engineer (essential)',
      'ISTQB Advanced Level – Test Manager (recommended)',
      'Cloud certifications (AWS, Azure) optional',
    ],
    yearsExperience: { min: 5, max: 15 },
    keywords: [
      'SDET',
      'test infrastructure',
      'automation architecture',
      'microservices testing',
      'contract testing',
      'test framework design',
      'CI/CD pipeline',
      'testability improvements',
      'test utilities',
      'performance testing',
      'advanced automation',
    ],
    interviewFocusAreas: [
      'Design a test automation framework from scratch for a microservices application',
      'How would you implement contract testing in a microservices environment?',
      'Describe your approach to building testable code with developers',
      'How do you handle testing in a distributed system?',
      'Tell me about a complex testing problem you solved',
      'How do you balance test automation with application development?',
      'Design a scalable CI/CD pipeline for testing',
    ],
  },

  // SPECIALISED TECHNICAL ROLES

  performance_tester: {
    id: 'performance_tester',
    title: 'Performance / Load Tester',
    category: 'specialized',
    level: 'mid',
    description: 'Measures system stability and speed under stress. Identifies bottlenecks in database, server configuration, or code logic using tools like JMeter or Gatling.',
    keyResponsibilities: [
      'Design and execute load testing scenarios',
      'Identify performance bottlenecks and capacity limits',
      'Analyze system behavior under stress',
      'Profile application and database performance',
      'Create performance test reports and recommendations',
      'Monitor production performance metrics',
      'Collaborate with infrastructure and development teams',
      'Establish performance baselines and SLAs',
    ],
    coreSkills: [
      'Performance testing methodology',
      'Load testing tool expertise',
      'Understanding of system architecture',
      'Database performance tuning basics',
      'Metrics and KPI analysis',
      'Scripting for test automation',
      'SQL and query optimization',
      'Network and infrastructure basics',
    ],
    technicalTools: [
      'JMeter (advanced)',
      'Gatling',
      'LoadRunner or Micro Focus',
      'Locust',
      'k6 or Artillery',
      'Grafana for metrics visualization',
      'Prometheus or CloudWatch (monitoring)',
      'New Relic or Dynatrace (APM)',
      'SQL profiling tools',
    ],
    certifications: [
      'ISTQB Foundation Level',
      'ISTQB Advanced Level – Performance Testing (recommended)',
      'JMeter certification (optional)',
    ],
    yearsExperience: { min: 3, max: 10 },
    keywords: [
      'performance testing',
      'load testing',
      'JMeter',
      'Gatling',
      'capacity planning',
      'bottleneck identification',
      'metrics analysis',
      'stress testing',
      'endurance testing',
      'performance optimization',
    ],
    interviewFocusAreas: [
      'Design a load test for an e-commerce platform during peak traffic',
      'How do you identify performance bottlenecks?',
      'What metrics do you track in performance testing?',
      'Describe your experience with JMeter/Gatling script development',
      'How do you determine realistic load scenarios?',
      'Tell me about a time you identified and helped fix a performance issue',
    ],
  },

  security_tester: {
    id: 'security_tester',
    title: 'Security Tester (Penetration Tester)',
    category: 'specialized',
    level: 'senior',
    description: 'Conducts ethical hacking and vulnerability assessments to protect data. Ensures compliance with security standards such as OWASP.',
    keyResponsibilities: [
      'Conduct penetration testing and vulnerability assessments',
      'Identify and document security vulnerabilities',
      'Test authentication and authorization mechanisms',
      'Assess data protection and encryption',
      'Review secure coding practices',
      'Create security test reports and remediation recommendations',
      'Ensure OWASP Top 10 compliance',
      'Collaborate with security and development teams',
    ],
    coreSkills: [
      'Ethical hacking and penetration testing methodology',
      'OWASP Top 10 and security vulnerabilities',
      'Web application security testing',
      'API security testing',
      'Network security basics',
      'Secure coding principles',
      'Incident response understanding',
      'Compliance standards (GDPR, PCI-DSS, SOC2)',
    ],
    technicalTools: [
      'Burp Suite (advanced)',
      'OWASP ZAP',
      'Metasploit',
      'Nessus',
      'Wireshark',
      'Postman with security testing',
      'SQLMap for SQL injection testing',
      'Acunetix',
      'Custom security test scripts',
    ],
    certifications: [
      'CEH (Certified Ethical Hacker)',
      'OSCP (Offensive Security Certified Professional)',
      'CompTIA Security+',
      'OWASP Certified',
    ],
    yearsExperience: { min: 5, max: 15 },
    keywords: [
      'security testing',
      'penetration testing',
      'vulnerability assessment',
      'OWASP',
      'ethical hacking',
      'security compliance',
      'data protection',
      'encryption',
      'authentication testing',
      'API security',
    ],
    interviewFocusAreas: [
      'Walk me through your penetration testing methodology',
      'How do you test for OWASP Top 10 vulnerabilities?',
      'Describe your experience with Burp Suite',
      'How do you approach API security testing?',
      'Tell me about a critical vulnerability you discovered and how you reported it',
      'How do you stay updated with emerging security threats?',
    ],
  },

  a11y_specialist: {
    id: 'a11y_specialist',
    title: 'Accessibility (A11y) Specialist',
    category: 'specialized',
    level: 'mid',
    description: 'Ensures applications are usable by people with disabilities, strictly adhering to WCAG 2.2 standards.',
    keyResponsibilities: [
      'Audit applications for accessibility compliance',
      'Test with assistive technologies (screen readers, voice control)',
      'Evaluate WCAG 2.2 AA/AAA compliance',
      'Create accessibility test plans and test cases',
      'Document accessibility issues and recommendations',
      'Mentor teams on accessible design principles',
      'Collaborate with UX/UI teams on design',
      'Test keyboard navigation and focus management',
    ],
    coreSkills: [
      'WCAG 2.2 standards and guidelines',
      'Assistive technology understanding',
      'Screen reader expertise',
      'Keyboard navigation testing',
      'Color contrast and visual design principles',
      'Semantic HTML knowledge',
      'ARIA (Accessible Rich Internet Applications)',
      'User empathy and inclusive design',
    ],
    technicalTools: [
      'axe DevTools',
      'WAVE (WebAIM tool)',
      'Lighthouse (Google Chrome DevTools)',
      'NVDA (free screen reader)',
      'JAWS (commercial screen reader)',
      'VoiceOver (Mac/iOS)',
      'Dragon NaturallySpeaking (voice control)',
      'Color contrast analyzer',
      'Accessibility auditing tools',
    ],
    certifications: [
      'IAAP CPACC (Certified Professional in Accessibility Core Competencies)',
      'IAAP WAS (Web Accessibility Specialist)',
      'WCAG certified specialist',
    ],
    yearsExperience: { min: 2, max: 10 },
    keywords: [
      'accessibility testing',
      'WCAG 2.2',
      'A11y',
      'assistive technology',
      'inclusive design',
      'screen reader testing',
      'keyboard navigation',
      'ARIA',
      'compliance testing',
      'accessible web',
    ],
    interviewFocusAreas: [
      'How do you approach accessibility testing for a web application?',
      'Describe your experience with WCAG 2.2 standards',
      'How would you test with a screen reader?',
      'What is ARIA and how do you test it?',
      'Tell me about a time you improved accessibility in an application',
      'How do you balance accessibility with modern design?',
    ],
  },

  api_tester: {
    id: 'api_tester',
    title: 'API / Integration Tester',
    category: 'specialized',
    level: 'mid',
    description: 'Focuses on the "headless" layer of the software. Validates data contracts, authentication, and communication between microservices.',
    keyResponsibilities: [
      'Design and execute API test cases',
      'Validate request/response contracts',
      'Test authentication and authorization',
      'Verify data integrity in API responses',
      'Test microservices integration',
      'Perform API performance testing',
      'Document API behavior and edge cases',
      'Create API test automation suites',
    ],
    coreSkills: [
      'REST API testing expertise',
      'GraphQL testing knowledge',
      'HTTP protocols and status codes',
      'JSON and XML expertise',
      'Data validation and schema testing',
      'Authentication methods (OAuth, JWT, API keys)',
      'Scripting for API automation',
      'Understanding of microservices architecture',
    ],
    technicalTools: [
      'Postman (advanced)',
      'REST Assured (Java/Groovy)',
      'Insomnia',
      'GraphQL clients (Apollo, GraphQL Playground)',
      'cURL and command-line tools',
      'Swagger/OpenAPI tools',
      'Contract testing (Pact)',
      'MockServer or Prism for API mocking',
      'API monitoring tools',
    ],
    certifications: [
      'ISTQB Foundation Level',
      'ISTQB Advanced Level – API Testing (if available)',
      'API testing certifications',
    ],
    yearsExperience: { min: 2, max: 8 },
    keywords: [
      'API testing',
      'REST API',
      'GraphQL',
      'Postman',
      'microservices testing',
      'integration testing',
      'contract testing',
      'data validation',
      'authentication testing',
      'API automation',
    ],
    interviewFocusAreas: [
      'How do you approach testing REST APIs?',
      'Describe your experience with Postman test automation',
      'How do you validate API responses?',
      'Tell me about testing GraphQL APIs',
      'How do you test authentication and authorization in APIs?',
      'Describe your experience with contract testing',
    ],
  },

  etl_tester: {
    id: 'etl_tester',
    title: 'ETL / Data Tester',
    category: 'specialized',
    level: 'mid',
    description: 'Specialises in verifying data integrity during migration or within Big Data environments, ensuring complex SQL queries and data pipelines are accurate.',
    keyResponsibilities: [
      'Design and execute ETL test cases',
      'Validate data migration accuracy',
      'Verify data transformation logic',
      'Test data quality and integrity',
      'Create data validation queries',
      'Monitor ETL pipeline execution',
      'Document data flow and dependencies',
      'Troubleshoot data issues',
    ],
    coreSkills: [
      'Advanced SQL query writing',
      'Data warehouse concepts',
      'ETL tool understanding',
      'Data validation techniques',
      'Excel/spreadsheet data analysis',
      'Understanding of data pipelines',
      'Data quality metrics',
      'Big Data concepts (basic Hadoop, Spark knowledge)',
    ],
    technicalTools: [
      'SQL (MySQL, PostgreSQL, Oracle, MySQL Server)',
      'Talend Data Quality',
      'Apache Nifi',
      'Apache Spark',
      'Python or R for data testing scripts',
      'Excel with advanced features',
      'Data profiling tools',
      'Informatica (for ETL monitoring)',
      'Tableau or Power BI (for data visualization)',
    ],
    certifications: [
      'ISTQB Foundation Level',
      'Advanced SQL certifications',
      'Data quality certifications',
    ],
    yearsExperience: { min: 3, max: 10 },
    keywords: [
      'ETL testing',
      'data migration',
      'data quality',
      'SQL testing',
      'data validation',
      'data pipeline',
      'data integrity',
      'big data testing',
      'data warehouse',
      'data transformation',
    ],
    interviewFocusAreas: [
      'How do you approach testing a data migration project?',
      'Describe your SQL skills and how you validate data',
      'How do you test ETL transformation logic?',
      'Tell me about data quality metrics you use',
      'How do you handle large datasets in testing?',
      'Describe a data integrity issue you found and how you resolved it',
    ],
  },

  ai_test_engineer: {
    id: 'ai_test_engineer',
    title: 'AI-Assisted Test Engineer',
    category: 'specialized',
    level: 'mid',
    description: 'Modern 2026 role specialising in using GenAI tools to generate test data, heal broken automation scripts, and analyse vast logs for defect patterns.',
    keyResponsibilities: [
      'Use GenAI for test case generation',
      'Leverage AI to heal broken automation scripts',
      'Analyse logs and defect patterns with AI',
      'Generate realistic test data using AI tools',
      'Implement AI-powered test automation',
      'Monitor and optimize AI tool usage',
      'Validate AI-generated test cases',
      'Stay current with AI/ML testing advancements',
    ],
    coreSkills: [
      'Prompt engineering for test generation',
      'Understanding of AI/ML fundamentals',
      'Test automation expertise',
      'Data analysis and pattern recognition',
      'Critical thinking about AI-generated content',
      'Traditional automation skills',
      'Python or JavaScript scripting',
      'Large Language Model (LLM) understanding',
    ],
    technicalTools: [
      'ChatGPT, Claude, or similar for prompting',
      'GitHub Copilot for code generation',
      'Playwright AI (visual regression)',
      'Test data generation AI tools',
      'Mabl or similar AI-powered testing platforms',
      'Advanced Selenium/Cypress',
      'Python automation frameworks',
      'Traditional test automation tools',
    ],
    certifications: [
      'ISTQB Foundation Level',
      'AI/ML fundamentals certifications',
      'GenAI tool-specific certifications',
    ],
    yearsExperience: { min: 3, max: 12 },
    keywords: [
      'AI testing',
      'GenAI',
      'prompt engineering',
      'AI-powered automation',
      'test data generation',
      'log analysis with AI',
      'ChatGPT testing',
      'intelligent test automation',
      'AI healing',
      'pattern recognition',
    ],
    interviewFocusAreas: [
      'How do you use GenAI tools for test case generation?',
      'Describe your experience using prompt engineering for testing',
      'How do you validate AI-generated test cases?',
      'Tell me about using AI to heal broken automation scripts',
      'How do you balance AI automation with traditional testing?',
      'What are the limitations of AI in test automation?',
    ],
  },

  // STRATEGIC & LEADERSHIP ROLES

  test_lead: {
    id: 'test_lead',
    title: 'Test Lead',
    category: 'strategic',
    level: 'lead',
    description: 'Operates at tactical level, managing testing schedule for specific project, allocating resources, and acting as bridge between developers and QA team.',
    keyResponsibilities: [
      'Manage testing schedules and timelines',
      'Allocate QA resources across projects',
      'Create test strategies and test plans',
      'Conduct test reviews and quality gates',
      'Mentor and manage QA team members',
      'Report test metrics and status to stakeholders',
      'Collaborate with product and development teams',
      'Identify and mitigate testing risks',
    ],
    coreSkills: [
      'Test planning and strategy',
      'Project management',
      'Risk assessment and mitigation',
      'Leadership and team management',
      'Communication and stakeholder management',
      'Quality metrics understanding',
      'Process improvement',
      'Vendor and tool evaluation',
    ],
    technicalTools: [
      'Test management platforms (TestRail, Azure Test Plans)',
      'Project management tools (Jira, Azure DevOps)',
      'Reporting tools (Tableau, Power BI)',
      'Atlassian suite (Jira, Confluence)',
      'Communication tools (Slack, Teams)',
      'Metrics and analytics platforms',
      'Basic automation knowledge required',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Level – Test Manager (essential)',
      'ISTQB Advanced Level – Test Analyst (recommended)',
      'Project management (PMP, PRINCE2) optional',
    ],
    yearsExperience: { min: 5, max: 15 },
    keywords: [
      'test lead',
      'test planning',
      'test strategy',
      'resource allocation',
      'team management',
      'quality metrics',
      'risk management',
      'stakeholder communication',
      'test scheduling',
      'tactical QA leadership',
    ],
    interviewFocusAreas: [
      'How do you create a test strategy for a new project?',
      'Describe your approach to resource allocation in QA',
      'How do you manage testing timelines and schedules?',
      'Tell me about a time you mitigated a testing risk',
      'How do you mentor junior QA team members?',
      'What metrics do you track to measure testing effectiveness?',
    ],
  },

  test_architect: {
    id: 'test_architect',
    title: 'Test Architect',
    category: 'strategic',
    level: 'lead',
    description: 'High-level technical visionary who decides tool stack for entire organisation. Ensures automation across departments is consistent and scalable.',
    keyResponsibilities: [
      'Design testing infrastructure and architecture',
      'Evaluate and select testing tools and frameworks',
      'Define automation standards and best practices',
      'Ensure consistency across multiple teams',
      'Design scalable test automation solutions',
      'Create testing CoE (Center of Excellence)',
      'Guide technical direction for QA teams',
      'Establish quality metrics and KPIs',
    ],
    coreSkills: [
      'Advanced automation architecture',
      'Testing strategy and roadmapping',
      'Tool evaluation and selection',
      'Scalability and performance concepts',
      'Technical leadership',
      'Cross-team collaboration',
      'Risk analysis and mitigation',
      'Vendor management',
    ],
    technicalTools: [
      'Advanced knowledge of: Selenium, Cypress, Playwright',
      'CI/CD platforms (Jenkins, GitHub Actions, GitLab CI)',
      'Test frameworks and design patterns',
      'Cloud platforms (AWS, Azure, GCP)',
      'Infrastructure as Code tools',
      'Monitoring and analytics platforms',
      'Documentation tools (Confluence, Wiki)',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Level – Test Manager (essential)',
      'ISTQB Advanced Level – Automation Engineer (recommended)',
      'Cloud certifications (AWS, Azure) optional',
    ],
    yearsExperience: { min: 8, max: 18 },
    keywords: [
      'test architect',
      'automation architecture',
      'tool selection',
      'testing infrastructure',
      'scalability',
      'CoE creation',
      'strategic testing',
      'framework design',
      'testing standards',
      'cross-team alignment',
    ],
    interviewFocusAreas: [
      'Describe your testing architecture vision for a large organization',
      'How do you evaluate and select testing tools?',
      'Tell me about establishing testing standards across teams',
      'How do you design scalable automation frameworks?',
      'Describe your approach to building a testing Center of Excellence',
      'How do you ensure consistency in automation practices?',
    ],
  },

  qa_manager: {
    id: 'qa_manager',
    title: 'QA Manager',
    category: 'strategic',
    level: 'lead',
    description: 'Strategic role focused on people management, budgeting, and defining long-term quality KPIs across multiple teams.',
    keyResponsibilities: [
      'Manage multiple QA teams and projects',
      'Build and expand QA team capacity',
      'Define quality KPIs and metrics',
      'Handle budgeting and resource planning',
      'Drive quality culture and processes',
      'Report quality status to senior management',
      'Career development for team members',
      'Process improvement initiatives',
    ],
    coreSkills: [
      'People management and leadership',
      'Budget planning and financial acumen',
      'Strategic planning and goal setting',
      'Quality metrics and KPIs',
      'Hiring and recruitment',
      'Stakeholder communication',
      'Change management',
      'Business acumen',
    ],
    technicalTools: [
      'HR systems and tools',
      'Financial management software',
      'Project management platforms',
      'Reporting and analytics tools',
      'Communication platforms',
      'Learning management systems',
      'Basic testing tool knowledge',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Level – Test Manager (essential)',
      'MBA or business management certifications (recommended)',
      'Leadership certifications optional',
    ],
    yearsExperience: { min: 8, max: 18 },
    keywords: [
      'QA manager',
      'people management',
      'team leadership',
      'budget planning',
      'quality KPIs',
      'strategic planning',
      'team expansion',
      'career development',
      'process improvement',
      'business acumen',
    ],
    interviewFocusAreas: [
      'How do you build and scale a QA team?',
      'Describe your approach to defining quality KPIs',
      'Tell me about a process improvement initiative you led',
      'How do you develop your team members?',
      'How do you handle QA budgeting?',
      'How do you communicate testing status to executive leadership?',
    ],
  },

  qa_director: {
    id: 'qa_director',
    title: 'Head of Quality / QA Director',
    category: 'strategic',
    level: 'executive',
    description: 'Executive-level role responsible for overall quality culture. Aligns QA processes with broader business objectives and digital transformation goals.',
    keyResponsibilities: [
      'Drive company-wide quality culture',
      'Align QA strategy with business objectives',
      'Lead digital transformation for testing',
      'Manage multiple QA departments and budgets',
      'Establish quality standards across the organization',
      'Report to C-suite on quality metrics',
      'Influence product direction through quality perspective',
      'Build strategic partnerships with tech vendors',
    ],
    coreSkills: [
      'Executive leadership and vision',
      'Strategic business planning',
      'Organizational change management',
      'Financial and budget management',
      'Board-level communication',
      'Digital transformation knowledge',
      'Vendor and partnership management',
      'C-suite collaboration',
    ],
    technicalTools: [
      'Executive reporting platforms',
      'Business intelligence tools',
      'Strategic planning tools',
      'Financial systems',
      'Communication platforms',
      'Enterprise software suites',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Level – Test Manager (essential)',
      'MBA or Executive Business Degree (recommended)',
      'Executive leadership certifications',
    ],
    yearsExperience: { min: 12, max: 25 },
    keywords: [
      'QA director',
      'head of quality',
      'executive leadership',
      'business strategy',
      'digital transformation',
      'quality culture',
      'organizational alignment',
      'strategic vision',
      'board reporting',
      'business acumen',
    ],
    interviewFocusAreas: [
      'What is your vision for quality in a modern technology organization?',
      'How do you align QA strategy with business objectives?',
      'Tell me about leading digital transformation initiatives',
      'How do you build and sustain a quality culture?',
      'Describe your approach to managing multiple QA teams',
      'How do you communicate quality metrics to the board?',
    ],
  },

  test_consultant: {
    id: 'test_consultant',
    title: 'Test Consultant',
    category: 'strategic',
    level: 'senior',
    description: 'External expert hired to audit company\'s current testing maturity and recommend improvements to processes, tools, or team structures.',
    keyResponsibilities: [
      'Conduct testing maturity assessments',
      'Audit current QA processes and practices',
      'Identify gaps and improvement opportunities',
      'Develop detailed recommendations and roadmaps',
      'Create implementation plans',
      'Train and mentor internal teams',
      'Advise on tool selections and investments',
      'Guide organizational transformation',
    ],
    coreSkills: [
      'Deep testing expertise across all areas',
      'Assessment and auditing methodologies',
      'Consulting and communication skills',
      'Industry best practices knowledge',
      'Change management guidance',
      'Strategic planning',
      'Training and mentoring',
      'Business analysis',
    ],
    technicalTools: [
      'Assessment frameworks (CMMI, TMMi)',
      'Analysis and documentation tools',
      'Presentation and reporting tools',
      'Video conferencing (for remote consulting)',
      'Project management tools',
      'Testing tools (broad knowledge required)',
    ],
    certifications: [
      'ISTQB Foundation Level (essential)',
      'ISTQB Advanced Levels (multiple recommended)',
      'Consulting certifications',
      'Industry-specific certifications',
    ],
    yearsExperience: { min: 10, max: 25 },
    keywords: [
      'test consultant',
      'testing maturity',
      'process improvement',
      'testing audit',
      'recommendations',
      'best practices',
      'organizational change',
      'tool evaluation',
      'training and mentoring',
      'strategic advice',
    ],
    interviewFocusAreas: [
      'Walk me through your approach to assessing testing maturity',
      'Tell me about a successful transformation you led',
      'How do you identify improvement opportunities in QA?',
      'Describe your experience with testing maturity models',
      'How do you handle resistance to change in organizations?',
      'What are the most common testing gaps you find?',
    ],
  },
};

/**
 * Helper function to get role details
 */
export function getQARole(roleId: string): QARole | undefined {
  return QA_ROLES[roleId];
}

/**
 * Helper to get all roles by category
 */
export function getRolesByCategory(category: 'core' | 'specialized' | 'strategic'): QARole[] {
  return Object.values(QA_ROLES).filter((role) => role.category === category);
}

/**
 * Helper to get all roles by level
 */
export function getRolesByLevel(level: 'entry' | 'mid' | 'senior' | 'lead' | 'executive'): QARole[] {
  return Object.values(QA_ROLES).filter((role) => role.level === level);
}

/**
 * Get role title by ID
 */
export function getRoleTitle(roleId: string): string {
  return QA_ROLES[roleId]?.title || 'Unknown Role';
}

/**
 * Get all role titles (for dropdowns, etc.)
 */
export function getAllRoleTitles(): { id: string; title: string }[] {
  return Object.entries(QA_ROLES).map(([id, role]) => ({
    id,
    title: role.title,
  }));
}
