// PDF export utility for CV Review results
import jsPDF from 'jspdf';

// Improved markdown stripping with content preservation
function stripMarkdown(text: string): string {
  if (!text) return '';
  
  return text
    // Remove headers but keep the text intact
    .replace(/^#{1,6}\s+(.+)$/gm, '$1')
    // Remove bold/italic but keep content (handle nested cases)
    .replace(/\*\*\*(.+?)\*\*\*/g, '$1')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    .replace(/_(.+?)_/g, '$1')
    // Fix edge case: remove stray markdown characters
    .replace(/\*\*|\*|__|_/g, '')
    // Remove parentheses artifacts from partial markdown
    .replace(/\(\*\*\)|\(\*\)/g, '')
    // Remove links but keep text
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
    // Remove inline code but keep content
    .replace(/`([^`]+)`/g, '$1')
    // Remove code blocks but keep content
    .replace(/```[\s\S]*?```/g, (match) => {
      return match.replace(/```\w*\n?/g, '').trim();
    })
    // Convert list markers
    .replace(/^[-*+]\s+/gm, '• ')
    .replace(/^\d+\.\s+/gm, '• ')
    // Remove horizontal rules
    .replace(/^[-*_]{3,}$/gm, '')
    // Clean up extra whitespace but preserve paragraph breaks
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

interface CVReviewResult {
  atsResume: string;
  interviewGuide: string;
  domainQuestions: string;
  gapAnalysis: string;
  optimizedCV?: string;
  coverLetter?: string;
  provider: 'gemini' | 'huggingface';
  generationTimeMs: number;
}

/**
 * Export CV review results to PDF
 */
export function exportToPDF(result: CVReviewResult): void {
  try {
    // Create new PDF document (A4 size)
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Page dimensions
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - (margin * 2);
    let y = margin;

    // Header - Brand Blueprint Color
    doc.setFillColor(0, 27, 68); // Deep blueprint (brand color)
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('CV Review & Interview Preparation', margin, 17);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by QaiTalk AI', margin, 26);
    
    // Reset text color to text-slate
    doc.setTextColor(30, 41, 59);
    y = 45;

    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate gray
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 6;
    doc.text(`Provider: ${result.provider === 'gemini' ? 'Google Gemini' : 'HuggingFace Llama'}`, margin, y);
    y += 6;
    doc.text(`Generation Time: ${(result.generationTimeMs / 1000).toFixed(1)}s`, margin, y);
    y += 12;

    // Reset color to text-slate
    doc.setTextColor(30, 41, 59);

    // Helper function to add sections with improved text handling
    const addSection = (doc: jsPDF, title: string, content: string) => {
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      
      // Check if we need a new page for the section header
      if (y + 25 > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }

      // Section header with background
      doc.setFillColor(248, 250, 252); // bg-cloud
      doc.rect(margin - 2, y - 7, contentWidth + 4, 16, 'F');
      // Add accent bar on left
      doc.setFillColor(0, 180, 216); // Logic cyan
      doc.rect(margin - 2, y - 7, 3, 16, 'F');
      doc.setFontSize(15);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 27, 68); // Deep blueprint
      doc.text(title, margin + 3, y);
      y += 15;

      // Section content
      doc.setTextColor(30, 41, 59); // Text-slate
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      
      // Split content into paragraphs first
      const paragraphs = content.split(/\n\n+/);
      
      for (const paragraph of paragraphs) {
        if (!paragraph.trim()) continue;
        
        const lines = doc.splitTextToSize(paragraph.trim(), contentWidth);
        
        for (const line of lines) {
          if (y + 7 > pageHeight - margin) {
            doc.addPage();
            y = margin;
          }
          doc.text(line, margin, y);
          y += 6; // 1.6 line height ratio (6mm for 11pt text)
        }
        
        // Add spacing between paragraphs
        y += 4;
      }
      
      // Add spacing after section
      y += 12;
    };

    // Section 1: ATS-Optimized Resume
    addSection(doc, '🎯 Strategic Role Analysis & ATS Optimisation', stripMarkdown(result.atsResume));

    // Section 2: Interview Guide
    addSection(doc, '🎭 Behavioural & Soft Skills Questions (5 STAR)', stripMarkdown(result.interviewGuide));

    // Section 3: Technical Questions
    addSection(doc, '💡 Domain-Specific Technical Questions (5 Questions)', stripMarkdown(result.domainQuestions));

    // Section 4: Gap Analysis
    addSection(doc, '📊 Skills Gap & Action Plan', stripMarkdown(result.gapAnalysis));

    // Section 5: Optimized CV (if available)
    if (result.optimizedCV) {
      addSection(doc, '📝 The Rewritten UK CV (with Six-Second Recruiter Test)', stripMarkdown(result.optimizedCV));
    }

    // Section 6: Cover Letter (if available)
    if (result.coverLetter) {
      addSection(doc, '✉️ Tailored UK Cover Letter', stripMarkdown(result.coverLetter));
    }

    // Add footer to all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139); // Slate gray
      doc.text(
        `Generated by QAi Talks CV Review Tool | qai-talks.com | Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }

    // Save the PDF
    const fileName = `CV_Review_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF export error:', error);
    throw new Error('Failed to export PDF');
  }
}

/**
 * Check if browser supports PDF export
 */
export function isPDFExportSupported(): boolean {
  return typeof window !== 'undefined' && typeof jsPDF !== 'undefined';
}
