// PDF export utility for CV Review results
import jsPDF from 'jspdf';

interface CVReviewResult {
  atsResume: string;
  interviewGuide: string;
  domainQuestions: string;
  gapAnalysis: string;
  provider: 'gemini' | 'huggingface';
  generationTimeMs: number;
}

/**
 * Export CV review results to PDF
 */
export function exportToPDF(result: CVReviewResult): void {
  try {
    // Create new PDF document (A4 size)
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Page dimensions
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - (margin * 2);
    let y = margin;

    // Header
    doc.setFillColor(15, 52, 96); // Deep blueprint
    doc.rect(0, 0, pageWidth, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('CV Review & Interview Preparation', margin, 15);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by QaiTalk AI', margin, 22);
    
    // Reset text color
    doc.setTextColor(0, 0, 0);
    y = 40;

    // Metadata
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 5;
    doc.text(`Provider: ${result.provider === 'gemini' ? 'Google Gemini' : 'HuggingFace Llama'}`, margin, y);
    y += 5;
    doc.text(`Generation Time: ${(result.generationTimeMs / 1000).toFixed(1)}s`, margin, y);
    y += 10;

    // Reset color
    doc.setTextColor(0, 0, 0);

    // Section 1: ATS-Optimized Resume
    addSection(doc, '📄 ATS-Optimized Resume Suggestions', result.atsResume);

    // Section 2: Interview Guide
    addSection(doc, '🎤 Interview Preparation Guide', result.interviewGuide);

    // Section 3: Technical Questions
    addSection(doc, '💡 Technical Domain Questions', result.domainQuestions);

    // Section 4: Gap Analysis
    addSection(doc, '📊 Skills Gap Analysis', result.gapAnalysis);

    // Footer on last page
    const currentPage = doc.getCurrentPageInfo().pageNumber;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by QaiTalk - https://qaitalks.com - Page ${currentPage}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    // Helper function to add sections
    function addSection(doc: jsPDF, title: string, content: string) {
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      
      // Check if we need a new page for the section
      if (y + 20 > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }

      // Section header with background
      doc.setFillColor(240, 248, 255);
      doc.rect(margin - 2, y - 5, contentWidth + 4, 10, 'F');
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 52, 96);
      doc.text(title, margin, y);
      y += 10;

      // Section content
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      const lines = doc.splitTextToSize(content, contentWidth);
      
      for (const line of lines) {
        if (y + 7 > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += 4;
      }
      
      y += 8; // Extra space after section
    }

    // Save the PDF
    const fileName = `CV_Review_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF export error:', error);
    throw new Error('Failed to export PDF');
  }
}

/**
 * Check if browser supports PDF export
 */
export function isPDFExportSupported(): boolean {
  return typeof window !== 'undefined' && typeof jsPDF !== 'undefined';
}
